#!/bin/bash
# Run MarkLogic as a service until it shuts down 
#

function stopml() 
{
  trap 'stopml' SIGINT SIGHUP SIGTERM SIGKILL
  service MarkLogic stop 
  while [ -f /var/run/MarkLogic.pid ] ; do 
     echo "Waiting for MarkLogic to exit" ; 
     ps -lp $(cat /var/run/MarkLogic.pid)
     sleep 10
  done
  exit 0
}

trap 'service MarkLogic stop' SIGINT SIGHUP SIGTERM SIGKILL
service MarkLogic start 
sleep 5
while ! [ -f /var/opt/MarkLogic/Logs/ErrorLog.txt ] ; do 
    sleep 1
done
tail -f /var/opt/MarkLogic/Logs/ErrorLog.txt &
disown %1 
sleep 1000000000
